### ISSUE TITLE
Environment variables don't override config/racecar.yml values

### ISSUE THREAD

**Issue by mrlevitas** [zendesk/racecar#174]
I noticed that I have to remove `brokers` from config/racecar.yml` for `RACECAR_BROKERS` to actually be effective.

e.g.
```
common: &common
  client_id: "xxx"

production:
  <<: *common
  brokers:
      - x
      - y
```

`x` & `y` take precedence over the values `RACECAR_BROKERS`.
Not sure if this is intended but seems it should be the other way around.
