### ISSUE TITLE
Cannot find ActiveRecord Class in Rails 6 uninitialized constant for Model in `app/models`

### ISSUE THREAD

**Issue by cdesch** [zendesk/racecar#249]
I have [RaceCar](https://github.com/zendesk/racecar) configured with in the rails `config/racecar.yml` like the the following:

```
  # These config values will be shared by all environments but can be overridden.
  common: &common
    client_id: "myapp"
    group_id: "myapp"
    log_level: "debug"
  
  development:
    <<: *common
    brokers:
      - kafka1:19092
  
  test:
    <<: *common
    brokers:
      - kafka1:19092
  
  production:
    <<: *common
    brokers:
      - kafka1:19092
```

and my consumer in app/consumers/transactions_consumer.rb:
```

class TransactionsConsumer < Racecar::Consumer
  subscribes_to "transactions", start_from_beginning: false

  def initialize
    Rails.logger.debug("Starting TransactionsConsumer")
  end


  def process(message)
    data = JSON.parse(message.value)
    puts data
    if Transaction.exists?(address: data["hash"])
      # Update the Transaction
      # Update the account 
    end
    
    if Address.exists?(address: data["fromAddress"])
      AccountBalanceUpdateJob.perform_in(1, data["fromAddress"])
    end

    if Address.exists?(address: data["toAddress"])
      AccountBalanceUpdateJob.perform_in(1, data["toAddress"])
    end
  rescue JSON::ParserError => e
    puts e
  end
end
```

I start the racecar with `command:  bash -c "bundle exec racecar TransactionsConsumer"` in a docker container via docker-compose so it can access kafka on the same network.

When messages come and the `TransactionConsumer` begins to process the message, I get a `uninitialized constant TransactionsConsumer::Address` error.  There should be no `TransactionsConsumer::Address` but it should find the `Address` class in `app/models/address.rb`.  Why am I getting this error? I am running Rails 6 but API only.

```
racecar_1  |   ↳ app/consumers/transactions_consumer.rb:19:in `process'
racecar_1  | E, [2021-05-24T20:45:00.417097 #1] ERROR -- : Failed to process transactions/0 at 21..21: uninitialized constant TransactionsConsumer::Address
racecar_1  | W, [2021-05-24T20:45:00.417124 #1]  WARN -- : Pausing partition transactions/0 for 10.0 seconds
racecar_1  | I, [2021-05-24T20:45:10.420964 #1]  INFO -- : Automatically resuming partition transactions/0, pause timeout expired
```
