### ISSUE TITLE
Racecar trying to connect to 127.0.0.1:9092 regardless of configuration

### ISSUE THREAD

**Issue by mhenrixon** [zendesk/racecar#259]
> E, [2021-08-27T08:39:32.093097 #9757] ERROR -- : rdkafka: [thrd:GroupCoordinator]: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)

```yaml
# config/racecar.yml
# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "my-consumer"

development:
  <<: *common
  brokers:
    - kafka:9092
 ```

```yaml
# docker-compose.yml
kafka:
    image: bashj79/kafka-kraft
    ports:
      - 9092:9092
    volumes:
      - kafka_logs:/tmp/kafka-logs
      - kafka_data:/var/lib/kafka/data
```

```console
RACECAR_BROKERS=kafka:9092 bin/racecar --brokers kafka:9092 MyTopicConsumer
```

Why am I trying to connect to `127.0.0.1:9092`? If I `ping kafka` I get:

```console
PING kafka (172.18.0.8): 56 data bytes
64 bytes from 172.18.0.8: seq=0 ttl=64 time=0.083 ms
64 bytes from 172.18.0.8: seq=1 ttl=64 time=0.114 ms
64 bytes from 172.18.0.8: seq=2 ttl=64 time=0.093 ms
64 bytes from 172.18.0.8: seq=3 ttl=64 time=0.106 ms
```

```ruby
class MyTopicConsumer < Racecar::Consumer
  subscribes_to "my-topic"

  self.parallel_workers = 5

  def process(message)
    puts "Received message: #{message.value}"
  end
end
```

```console
bin/racecar -v
#=> Racecar 2.3.0
```
